name: Docker Image Build ðŸ‹

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master, production ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ðŸ›Žï¸
      uses: actions/checkout@v2
    - name: Checkout submodules ðŸ›Žï¸
      uses: textbook/git-checkout-submodule-action@master
    - name: Set up QEMU ðŸ”§
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Build the Docker Image ðŸ‹
      run: docker build . -t simplesignage
    - name: Save the Docker Image ðŸ’¾
      run: docker save simplesignage > SimpleSignage.tar
    - name: Upload Docker Image âœˆ
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: ./SimpleSignage.tar
