name: Docker Image Build ðŸ‹

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ðŸ›Žï¸
      uses: actions/checkout@v2
    - name: Set up QEMU ðŸ”§
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Build the Docker Image ðŸ‹
      run: IMGTAG=$(date +%s) && docker build . -t simplesignage:$IMGTAG
    - name: Save the Docker Image ðŸ’¾
      run: docker save simplesignage:$IMGTAG > SimpleSignage.tar
    - name: Upload Docker Image âœˆ
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: ./SimpleSignage.tar
